language: php

php:
- 7.0

before_install:
- composer global require hirak/prestissimo

install:
- sudo apt-get install wput
- composer self-update
- composer install
- nvm install 6
- npm install --global ied
- npm install --global rxjs@5.0.0-rc.1
- npm install --global grunt-cli
- ied install

script:
- grunt

after_script:
- cd build && wput . $FTP_URL --reupload

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
