language: php

php: 7.2

addons:
 apt:
  packages:
  - lftp
 ssh_known_hosts:
 - w00976cb.kasserver.com

before_install:
- composer global require hirak/prestissimo

install:
- composer install
- nvm install 12
- npm install --global grunt-cli
- npm install
- cd vendor/redaxscript/redaxscript && npm install && cd -

script:
- grunt build --gruntfile vendor/redaxscript/redaxscript/gruntfile.js
- grunt

after_success:
- grunt validateBuild
- grunt deploy
- grunt download
- grunt validateDownload

notifications:
 email:
 - team@redaxscript.com
