language: php

php:
- 7.0

before_install:
- composer global require hirak/prestissimo

install:
- sudo apt-get install wput
- sudo apt-get install lftp
- composer self-update
- composer install
- nvm install 6
- npm install --global ied
- npm install --global grunt-cli
- ied install

script:
- grunt

after_script:
- sh test.sh build/*/*.zip
- lftp $FTP_URL -e "rm -rf ."; exit;
- cd build && wput . $FTP_URL && cd ..
- wget . $FTP_URL --recursive --no-host-directories --directory-prefix download
- sh test.sh download/*/*.zip

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
