language: php

php:
- 7.0

before_install:
- composer global require hirak/prestissimo

install:
- sudo apt-get install lftp
- composer self-update
- composer install
- nvm install 6
- npm install --global ied
- npm install --global grunt-cli
- ied install

script:
- grunt

after_script:
- sh validate.sh build/*/*.zip
- lftp $FTP_URL -e "glob -d mirror build . --reverse --delete-first --parallel=10 && exit"
- lftp $FTP_URL -e "glob -d mirror . download --delete-first --parallel=10 && exit"
- sh validate.sh download/*/*.zip

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
