language: php

install:
- composer self-update
- composer install
- nvm install 6
- npm install --global ied
- npm install --global grunt-cli

script:
- php -v

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
