language: php

php:
- 7.1

before_install:
- composer global require hirak/prestissimo

install:
- sudo apt-get install lftp fontforge
- composer self-update
- composer install
- nvm install 6
- npm install --global ied
- npm install --global grunt-cli
- IED_CACHE_DIR=.tmp ied install
- cd vendor/redaxscript/redaxscript && IED_CACHE_DIR=.tmp ied install && cd -

script:
- grunt build --gruntfile vendor/redaxscript/redaxscript/gruntfile.js
- grunt

after_success:
- grunt validateBuild
- lftp $FTP_URL -e "glob -d mirror build . --reverse --delete-first --parallel=10 && exit"
- lftp $FTP_URL -e "glob -d mirror . download --delete-first --parallel=10 && exit"
- grunt validateDownload

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
