language: php

php:
- 7.0

install:
- composer self-update
- composer install
- nvm install 6
- npm install --global ied
- npm install --global grunt-cli
- ied install

script:
- grunt

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
